image: ${GV_REGISTRY_ADDRESS}/${GV_BUILD_IMAGE_NAME}

cache:
  key: ${CI_PROJECT_PATH_SLUG}
  paths:
    - .m2/repository/

variables:
  DOMAIN: "testtool"
  LABELS: "essential"

include:
  - project: 'infr/pipelines/service/ci/common'
    ref: v2
    file: '/public/java/mvn/gitflow.yml'
  - project: 'infr/pipelines/service/ci/common'
    ref: v2
    file: '/public/conf/definition.yml'
  - project: 'infr/pipelines/service/ci/common'
    ref: v2
    file: '/public/conf/gitflow.yml'

  - project: 'infr/pipelines/service/cd/common'
    ref: v2
    file: '/public/definition.yml'
  - project: 'infr/pipelines/service/cd/common'
    ref: v2
    file: '/public/gitflow.yml'
  - project: 'infr/pipelines/service/cd/common'
    ref: v2
    file: '/public/features/deploy_from_feature_branch.yml'
