image: ${GV_REGISTRY_ADDRESS}/${GV_BUILD_IMAGE_NAME}

cache:
  key: ${CI_PROJECT_PATH_SLUG}
  paths:
    - .m2/repository/

include:
  - project: 'infr/pipelines/service/ci/common'
    ref: master
    file: '/public/java/mvn/gitflow.yml'
  - project: 'infr/pipelines/service/ci/common'
    ref: master
    file: '/public/conf/definition.yml'
  - project: 'infr/pipelines/service/ci/common'
    ref: master
    file: '/public/conf/gitflow.yml'
  - project: 'infr/pipelines/service/cd/common'
    ref: master
    file: '/public/definition.yml'
  - project: 'infr/pipelines/service/cd/common'
    ref: master
    file: '/public/gitflow.yml'
  - project: 'infr/pipelines/service/cd/common'
    ref: master
    file: '/public/domain/acc.yml'



