version: "3"
services:
#  etcd:
#    image: quay.io/coreos/etcd:v3.4.7
#    container_name: etcd
#    ports:
#      - 2379:2379
#      - 2380:2380
#    restart: always
#    volumes:
#      - data_volume:/etcd-data
#    environment:
#      - NODE1=127.0.0.1
#      - ETCDCTL_API=3
#    command:
#      - /usr/local/bin/etcd
#      - --data-dir=/etcd-data
#      - --name
#      - node1
#      - --initial-advertise-peer-urls
#      - http://127.0.0.1:2380
#      - --listen-peer-urls
#      - http://0.0.0.0:2380
#      - --advertise-client-urls
#      - http://127.0.0.1:2379
#      - --listen-client-urls
#      - http://0.0.0.0:2379
#      - --initial-cluster
#      - node1=http://127.0.0.1:2380
  postgres-vvi:
    container_name: postgres-vvi
    restart: always
    image: postgres:9.6
    volumes:
      - postgres-vvi:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgresvvi
      POSTGRES_DB: postgresvvi
  dozzle:
    container_name: dozzle
    restart: always
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
  coh:
    container_name: coh
    restart: always
    image: mtr.external.otc.telekomcloud.com/digitalhub/customer-order-handler:328
    depends_on:
      - postgres-coh
      - mq
    ports:
      - 8080:8080
    environment:
      - BL_CRM_ADAPTER_BASE_URL=http://localhost:8080
      - MQ_HOSTNAME=mq
      - MQ_PORT=1414
      - MQ_CONNECTION_ENABLED=true
      - COH_MOCK_AUFTRAGNUMBER_ENABLE=true
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-coh:5432/postgres
      - ENV_TYPE=dev
  mocktool:
    container_name: mocktool
    restart: always
    image: mtr.external.otc.telekomcloud.com/digitalhub/mocktool-proto:36
    depends_on:
      - postgres-mocktool
      - mq
    ports:
      - 8081:8080
    environment:
      - MOCKTOOL_IBM_MQ_HOSTNAME=mq
      - MOCKTOOL_IBM_MQ_PORT=1414
      - SPRING_DATASOURCE_USERNAME=postgres-mocktool
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-mocktool:5432/postgres-mocktool
  mq:
    container_name: mq
    restart: always
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ENABLE_EMBEDDED_WEB_SERVER=false
  postgres-coh:
    container_name: postgres-coh
    restart: always
    image: postgres:9.6
    volumes:
      - postgres-coh:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  postgres-mocktool:
    container_name: postgres-mocktool
    restart: always
    image: postgres:9.6
    volumes:
      - postgres-mocktool:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres-mocktool
      POSTGRES_DB: postgres-mocktool
  postgres-pch:
    container_name: postgres-pch
    restart: always
    image: postgres:9.6
    volumes:
      - postgres-pch:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgrespch
      POSTGRES_DB: postgrespch
volumes:
  data_volume:
  postgres-vvi:
  postgres-coh:
  postgres-pch:
  postgres-mocktool: