global:
  project_prefix: "gigabit-tm-"
  domains:
    internal:
      expose: true
    external:
      expose: true
  namespace: "NonExsitenteAsItShouldBeSuppliedAtRunTime"

app_name: &app_name_definition "wiremock-acc"

app:
  name: *app_name_definition
  image:
    name: *app_name_definition
  health:
    url: "/__admin/mappings?limit=1"
  prometheus: false
  scaling_denied: true
  env:
    params:
      CLIENT_ID: *app_name_definition
      CLIENT_SECRET: "gohgua4ahLaP9quei7go"
      PROVIDER_CLIENT_ID: "wiremock-provider-client"
      PUBLIC_CLIENT_ID: "wiremock-public-client"
      OAL_CONNECTION_PATH: "http://oal-connection-app"
      GROOVY_ROOT: "./groovy"
    inject_maps:
      - "apigw-endpoints"
      - "rhsso-endpoints"
