/*
 * rhsso
 * rhsso
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tsystems.tm.acc.wiremock.oauth.client.invoker;

import com.tsystems.tm.acc.wiremock.oauth.client.api.RhssoApi;
import io.restassured.builder.RequestSpecBuilder;

import java.util.function.Supplier;

import static com.tsystems.tm.acc.wiremock.oauth.client.invoker.GsonObjectMapper.gson;
import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;


public class ApiClient {
    public static final String BASE_URI = "http://localhost/auth/realms/GigabitHub/protocol/openid-connect";

    private final Config config;

    private ApiClient(Config config) {
        this.config = config;
    }

    public static ApiClient api(Config config) {
        return new ApiClient(config);
    }

    public RhssoApi rhsso() {
        return RhssoApi.rhsso(config.reqSpecSupplier);
    }

    public static class Config {
        private Supplier<RequestSpecBuilder> reqSpecSupplier = () -> new RequestSpecBuilder()
                .setBaseUri(BASE_URI)
                .setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())));

        /**
         * Use common specification for all operations
         *
         * @param supplier supplier
         * @return configuration
         */
        public Config reqSpecSupplier(Supplier<RequestSpecBuilder> supplier) {
            this.reqSpecSupplier = supplier;
            return this;
        }

        public static Config apiConfig() {
            return new Config();
        }
    }
}